server:
  port: 80

spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: localhost
    port: 6379
jwt:
  secret:

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/toon
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

app:
  resource: src/main/resources/static/
  toon:
    dir: src/main/resources/static/toons
  user:
    image:
      dir: src/main/resources/static/profileImages
---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:postgresql://localhost:5432/test_toon
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

app:
  resource: src/test/resources/static
  toon:
    dir: src/test/resources/toons
  user:
    image:
      dir: src/test/resources/profileImages
